services:
  - type: web
    name: legal-ai-assistant
    env: python
    plan: starter
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DATABASE_URL
        fromDatabase:
          name: legal-ai-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: legal-ai-redis
          property: connectionString
      - key: GOOGLE_DRIVE_CLIENT_ID
        sync: false
      - key: GOOGLE_DRIVE_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SENTENCE_TRANSFORMER_MODEL
        value: all-MiniLM-L6-v2
      - key: FAISS_INDEX_PATH
        value: ./ml_models/faiss_index.bin
      - key: CLASSIFIER_MODEL_PATH
        value: ./ml_models/legal_classifier.pkl

  - type: postgresql
    name: legal-ai-db
    plan: starter
    ipAllowList: []

  - type: redis
    name: legal-ai-redis
    plan: starter
    ipAllowList: []